# Generated by Django 2.2.7 on 2019-12-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='player',
            name='college',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='pos',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
