# Generated by Django 2.2.7 on 2019-12-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191207_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='letter',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
