# Generated by Django 2.2.7 on 2019-12-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='letter',
            new_name='letter_char',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='pos',
            new_name='pos_key',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team',
            new_name='team_name',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField()),
                ('players', models.ManyToManyField(to='core.Player')),
            ],
            options={
                'ordering': ['team_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_key', models.TextField()),
                ('players', models.ManyToManyField(to='core.Player')),
            ],
            options={
                'ordering': ['position_key'],
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_char', models.CharField(max_length=1)),
                ('players', models.ManyToManyField(to='core.Player')),
            ],
            options={
                'ordering': ['letter_char'],
            },
        ),
    ]
