# Generated by Django 2.2.7 on 2019-12-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191208_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['team_key']},
        ),
        migrations.AddField(
            model_name='team',
            name='team_key',
            field=models.CharField(default='N', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='pos_key',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='position',
            name='pos_key',
            field=models.CharField(max_length=2),
        ),
    ]
