# Generated by Django 2.2.7 on 2019-12-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191208_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fantasy_pts',
            field=models.IntegerField(default=0),
        ),
    ]
