# Generated by Django 2.2.7 on 2019-12-09 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0008_auto_20191208_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasyteam',
            name='owner',
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FantasyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fantasy_teams', models.ManyToManyField(to='core.FantasyTeam')),
            ],
            options={
                'ordering': ['username'],
            },
            bases=('auth.user',),
        ),
    ]
