# Generated by Django 2.2.7 on 2019-12-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_fantasyuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fantasyteam',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='fantasyteam',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
