# Generated by Django 2.2.7 on 2019-12-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191209_0620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'ordering': ['owner_id']},
        ),
        migrations.RemoveField(
            model_name='roster',
            name='fantasy_team_name',
        ),
        migrations.AddField(
            model_name='roster',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='roster',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
    ]
