# Generated by Django 2.2.7 on 2019-12-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191209_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='finished_drafting',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='FantasyTeam',
        ),
    ]
