# Generated by Django 2.2.7 on 2019-12-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191210_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='finished_drafting',
        ),
    ]
