# Generated by Django 2.2.7 on 2019-12-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_roster_finished_drafting'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stats_url',
            field=models.CharField(default='https://www.footballdb.com/players/', max_length=100),
            preserve_default=False,
        ),
    ]
