# Generated by Django 2.2.7 on 2019-12-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_player_stats_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fantasy_pts',
            field=models.FloatField(default=0.0),
        ),
    ]
